apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  annotations:
    commit.image.appsody.dev/author: Khairul Habib <khairul.habib@ibm.com>
    commit.image.appsody.dev/committer: Khairul Habib <khairul.habib@ibm.com>
    commit.image.appsody.dev/date: Mon Mar 23 07:47:52 2020 +0700
    commit.image.appsody.dev/message: add new controller
    image.opencontainers.org/created: "2020-03-23T11:37:43+07:00"
    image.opencontainers.org/documentation: https://github.com/khairulhabibatibm/microapp
    image.opencontainers.org/revision: 94465bc89fcb3d11a6358aa69653a8d8b191e6df-modified
    image.opencontainers.org/source: https://github.com/khairulhabibatibm/microapp/tree/master
    image.opencontainers.org/url: https://github.com/khairulhabibatibm/microapp
    stack.appsody.dev/authors: Emily Jiang <emijiang6@googlemail.com>, Neeraj Laad
      <neeraj.laad@gmail.com>, Ozzy <ozzy@ca.ibm.com>
    stack.appsody.dev/configured: docker.io/appsody/java-microprofile:0.2
    stack.appsody.dev/created: "2020-02-13T09:06:53Z"
    stack.appsody.dev/description: Eclipse MicroProfile on Open Liberty & OpenJ9 using
      Maven
    stack.appsody.dev/licenses: Apache-2.0
    stack.appsody.dev/tag: docker.io/appsody/java-microprofile:0.2.24
    stack.appsody.dev/title: Eclipse MicroProfile®
  creationTimestamp: null
  labels:
    image.opencontainers.org/title: microapp
    stack.appsody.dev/id: java-microprofile
    stack.appsody.dev/version: 0.2.24
  name: microapp
spec:
  applicationImage: khairulhabib/microapp:1.4
  createKnativeService: false
  expose: true
  livenessProbe:
    failureThreshold: 12
    httpGet:
      path: /health/live
      port: 9080
    initialDelaySeconds: 5
    periodSeconds: 2
  readinessProbe:
    failureThreshold: 12
    httpGet:
      path: /health/ready
      port: 9080
    initialDelaySeconds: 5
    periodSeconds: 2
    timeoutSeconds: 1
  service:
    annotations:
      prometheus.io/scrape: "true"
    port: 9080
    type: NodePort
  stack: java-microprofile
  version: 1.0.0
